    services:
      app:
        build: .
        depends_on:
          db:
            condition: service_healthy
        container_name: go-api-container
        env_file:
          - .env
        networks:
          - app-network
        restart: always
      db:
        image: mysql:8.0
        container_name: go-db-container
        env_file:
          - .env
        volumes:
          - ./dump:/docker-entrypoint-initdb.d # Use a named volume for persistent data storage
        networks:
          - app-network
        restart: always
        ports:
          - "3307:3307"
        healthcheck:
          test: ["CMD-SHELL", "mysql --user=$$DBUSER --password=$$DBPASS --execute \"SHOW DATABASES;\" || exit 1"]
          timeout: 60s
          retries: 5
  
    volumes:
      mysql-data:   # Declare a named volume to persist MySQL data
        driver: local

    networks:
      app-network:
        driver: bridge