    version: "3.8"
    services:
      app:
        build: .
        container_name: go-api-container
        env_file:
          - .env
        ports:
          - "8080:8080"
        depends_on:
          - db
        networks:
          - app-network
        restart: always
      db:
        image: mysql:8.0
        container_name: go-db-container
        env_file:
          - .env
        volumes:
          - ./dump:/docker-entrypoint-initdb.d # Use a named volume for persistent data storage
        networks:
          - app-network
        restart: always
        ports:
          - "3306:3306"
  
    volumes:
      mysql-data:   # Declare a named volume to persist MySQL data
        driver: local

    networks:
      app-network:
        driver: bridge